LOAD DATA
INFILE 'C:\OMOP_VOCAB\CONCEPT.csv'
APPEND INTO TABLE CONCEPT
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
    CONCEPT_ID,
    CONCEPT_NAME CHAR(255),
    DOMAIN_ID CHAR(20),
    VOCABULARY_ID CHAR(20),
    CONCEPT_CLASS_ID CHAR(20),
    STANDARD_CONCEPT CHAR(1),
    CONCEPT_CODE CHAR(50),
    VALID_START_DATE DATE "YYYY-MM-DD",
    VALID_END_DATE DATE "YYYY-MM-DD",
    INVALID_REASON CHAR(1)
)
