LOAD DATA
INFILE 'C:\OMOP_VOCAB\CONCEPT_ANCESTOR.csv'
APPEND INTO TABLE CONCEPT_ANCESTOR
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
    ANCESTOR_CONCEPT_ID,
    DESCENDANT_CONCEPT_ID,
    MIN_LEVELS_OF_SEPARATION,
    MAX_LEVELS_OF_SEPARATION
)
