LOAD DATA
INFILE 'C:\OMOP_VOCAB\CONCEPT_RELATIONSHIP.csv'
APPEND INTO TABLE CONCEPT_RELATIONSHIP
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
    CONCEPT_ID_1,
    CONCEPT_ID_2,
    RELATIONSHIP_ID CHAR(20),
    VALID_START_DATE DATE "YYYY-MM-DD",
    VALID_END_DATE DATE "YYYY-MM-DD",
    INVALID_REASON CHAR(1)
)
